{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: chatbot
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
{{- end }}
